/*
 * hnx_selftest.c — does the C decoder agree with the Python encoder?
 *
 * This is the test that matters, and it is the reason the decoder is a
 * standalone C file rather than a patch buried in ggml. A bit order or
 * a group stride that is wrong by one produces a model that loads
 * successfully, runs at full speed, and emits fluent nonsense. Nothing
 * about that failure looks like a failure, so it has to be caught by
 * comparison against the implementation that wrote the file.
 *
 * Two modes:
 *
 *   hnx_selftest                 self-contained checks: block sizes,
 *                                FP16 round trips, the sign/repeat
 *                                mapping, dot == dequantise-then-dot
 *
 *   hnx_selftest vectors.bin     compare against vectors generated by
 *                                hypernix.quant.subbit (see
 *                                tools/gen_vectors.py). Each record is
 *                                a type id, the packed block, and the
 *                                256 floats Python decoded it to.
 *
 * Exits non-zero on the first disagreement, naming the type, the block
 * and the element. A silent pass here is the only evidence that the two
 * implementations mean the same thing by "IQ0.5_XXXL".
 */
#include "ggml-hnx.h"

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int failures = 0;

static void fail(const char *what, const char *detail) {
    fprintf(stderr, "FAIL %s: %s\n", what, detail);
    failures++;
}

static void check(int condition, const char *what) {
    if (condition) {
        printf("  ok   %s\n", what);
    } else {
        fail(what, "condition was false");
    }
}

/* --- block geometry ----------------------------------------------------- */

static void test_block_sizes(void) {
    printf("block geometry\n");
    struct { int type; size_t bytes; float bpw; } expected[] = {
        { HNX_TYPE_IQ0_9,  30, 0.9375f },
        { HNX_TYPE_IQ0_75, 26, 0.8125f },
        { HNX_TYPE_IQ0_5,  18, 0.5625f },
        { HNX_TYPE_IQ0_25,  8, 0.2500f },
        { HNX_TYPE_INT1,   34, 1.0625f },
    };
    for (size_t i = 0; i < sizeof(expected) / sizeof(expected[0]); i++) {
        char label[96];
        const hnx_type_info *info = hnx_type_lookup(expected[i].type);
        if (info == NULL) { fail("type lookup", "unknown type id"); continue; }

        snprintf(label, sizeof(label), "%s is %zu bytes per block",
                 info->name, expected[i].bytes);
        check(hnx_block_bytes(expected[i].type) == expected[i].bytes, label);

        /* The published bits-per-weight has to be what the layout
         * actually gives, or the tier is advertising a size it does not
         * deliver -- which is the exact bug the sub-bit work fixed on
         * the Python side. */
        snprintf(label, sizeof(label), "%s really is %.4f bits/weight",
                 info->name, expected[i].bpw);
        const float actual = (float)(expected[i].bytes * 8) / (float)HNX_BLOCK_SIZE;
        check(fabsf(actual - expected[i].bpw) < 1e-6f, label);

        /* group and kept have to be consistent with the block size, or
         * the decoder walks off the payload. */
        const size_t codes = HNX_BLOCK_SIZE / (size_t)info->group;
        const size_t payload = (codes * (size_t)info->kept + 7) / 8;
        snprintf(label, sizeof(label), "%s payload arithmetic closes", info->name);
        check(payload + 2 == expected[i].bytes, label);
    }
}

/* --- FP16 --------------------------------------------------------------- */

static void test_fp16(void) {
    printf("fp16\n");
    /* Values that exercise the paths: zero, a normal, the smallest
     * normal, a subnormal, the maximum, and a negative. */
    const float values[] = {
        0.0f, 1.0f, -1.0f, 0.5f, 0.125f, 6.103515625e-05f,
        5.960464477539063e-08f, 65504.0f, -65504.0f, 0.0078125f,
    };
    for (size_t i = 0; i < sizeof(values) / sizeof(values[0]); i++) {
        const float back = hnx_fp16_to_fp32(hnx_fp32_to_fp16(values[i]));
        char label[96];
        snprintf(label, sizeof(label), "%g survives a round trip", (double)values[i]);
        check(back == values[i], label);
    }
    check(hnx_fp16_to_fp32(0x0000u) == 0.0f, "0x0000 is zero");
    check(hnx_fp16_to_fp32(0x3C00u) == 1.0f, "0x3C00 is one");
    check(hnx_fp16_to_fp32(0xBC00u) == -1.0f, "0xBC00 is minus one");
    check(isinf(hnx_fp16_to_fp32(0x7C00u)), "0x7C00 is infinity");
    check(isnan(hnx_fp16_to_fp32(0x7E00u)), "0x7E00 is NaN");
    /* A NaN scale must stay NaN rather than becoming an infinity: the
     * two dequantise a block very differently and only one of them is
     * detectable downstream. */
    check(isnan(hnx_fp16_to_fp32(hnx_fp32_to_fp16(NAN))), "NaN stays NaN");
}

/* --- the sign and repeat mapping ---------------------------------------- */

static void test_sign_mapping(void) {
    printf("sign mapping\n");
    /* IQ0.5: group 4, 2 signs kept. Build a block by hand with a known
     * scale and known bits, then check every one of the 256 outputs. */
    hnx_block_iq0_5 block;
    memset(&block, 0, sizeof(block));
    block.d = hnx_fp32_to_fp16(0.25f);
    /* First group: bit0 = 1 (+), bit1 = 0 (-). So + - - -, because the
     * two dropped positions repeat the last stored sign, which is -. */
    block.qs[0] = 0x01;

    float out[HNX_BLOCK_SIZE];
    check(hnx_dequantize_block(HNX_TYPE_IQ0_5, &block, out) == 0, "IQ0.5 decodes");
    check(out[0] ==  0.25f, "stored + is +scale");
    check(out[1] == -0.25f, "stored - is -scale");
    check(out[2] == -0.25f, "dropped position repeats the last stored sign");
    check(out[3] == -0.25f, "and so does the one after it");

    /* IQ0.25 is the one that had the bug: group 16, 3 kept, so the bit
     * cursor advances by 3 per group and not by 16. If it advanced by
     * the group the second group would read bits 16..18 instead of
     * 3..5 -- and every weight after the first sixteen would be wrong
     * while the model still ran. */
    hnx_block_iq0_25 quarter;
    memset(&quarter, 0, sizeof(quarter));
    quarter.d = hnx_fp32_to_fp16(1.0f);
    /* bits 0,1,2 = 0 (first group all -), bits 3,4,5 = 1 (second all +). */
    quarter.qs[0] = 0x38;   /* 0b00111000 */
    check(hnx_dequantize_block(HNX_TYPE_IQ0_25, &quarter, out) == 0,
          "IQ0.25 decodes");
    check(out[0] == -1.0f && out[15] == -1.0f, "first group is all -");
    check(out[16] == 1.0f && out[31] == 1.0f,
          "second group reads the next 3 bits, not the next 16");

    /* INT1: group 1, 1 kept. Nothing is reconstructed, so every weight
     * gets its own sign and the scale is the only loss. */
    hnx_block_int1 binary;
    memset(&binary, 0, sizeof(binary));
    binary.d = hnx_fp32_to_fp16(2.0f);
    binary.qs[0] = 0xAA;   /* - + - + - + - + , LSB first */
    check(hnx_dequantize_block(HNX_TYPE_INT1, &binary, out) == 0, "INT1 decodes");
    check(out[0] == -2.0f && out[1] == 2.0f && out[2] == -2.0f,
          "INT1 keeps every sign");
}

/* --- round trip and dot ------------------------------------------------- */

static void test_round_trip_and_dot(void) {
    printf("round trip and dot product\n");
    const int types[] = { HNX_TYPE_IQ0_9, HNX_TYPE_IQ0_75, HNX_TYPE_IQ0_5,
                          HNX_TYPE_IQ0_25, HNX_TYPE_INT1 };
    const size_t nblocks = 3;

    float weights[3 * HNX_BLOCK_SIZE];
    float other[3 * HNX_BLOCK_SIZE];
    for (size_t i = 0; i < nblocks * HNX_BLOCK_SIZE; i++) {
        /* Deterministic, mixed sign, nothing exactly zero. */
        weights[i] = (float)(((int)(i * 37u) % 41) - 20) / 7.0f;
        other[i] = (float)(((int)(i * 53u) % 29) - 14) / 3.0f;
    }

    for (size_t t = 0; t < sizeof(types) / sizeof(types[0]); t++) {
        const hnx_type_info *info = hnx_type_lookup(types[t]);
        unsigned char packed[3 * 64];
        char label[128];

        const size_t written = hnx_quantize_rows(types[t], weights, packed,
                                                 nblocks, NULL);
        snprintf(label, sizeof(label), "%s packs %zu blocks", info->name, nblocks);
        check(written == nblocks * info->block_bytes, label);

        float decoded[3 * HNX_BLOCK_SIZE];
        const size_t count = hnx_dequantize_rows(types[t], packed, decoded, nblocks);
        snprintf(label, sizeof(label), "%s unpacks to %zu floats", info->name,
                 nblocks * HNX_BLOCK_SIZE);
        check(count == nblocks * HNX_BLOCK_SIZE, label);

        /* Every decoded weight is +/- the block's scale and nothing
         * else. This is the defining property of the family: if a
         * decoder ever produced a third magnitude it would mean the
         * payload was being read as data rather than as signs. */
        int only_two_magnitudes = 1;
        for (size_t b = 0; b < nblocks; b++) {
            uint16_t raw;
            memcpy(&raw, packed + b * info->block_bytes, sizeof(raw));
            const float scale = hnx_fp16_to_fp32(raw);
            for (size_t i = 0; i < HNX_BLOCK_SIZE; i++) {
                const float value = decoded[b * HNX_BLOCK_SIZE + i];
                if (value != scale && value != -scale) only_two_magnitudes = 0;
            }
        }
        snprintf(label, sizeof(label), "%s decodes to +/-scale only", info->name);
        check(only_two_magnitudes, label);

        /* The fast path has to agree with the slow one. hnx_vec_dot
         * never materialises the row, which is the whole point of it,
         * and that is exactly the kind of optimisation that quietly
         * disagrees. */
        float expected = 0.0f;
        for (size_t i = 0; i < nblocks * HNX_BLOCK_SIZE; i++) {
            expected += decoded[i] * other[i];
        }
        const float actual = hnx_vec_dot(types[t], packed, other, nblocks);
        snprintf(label, sizeof(label), "%s vec_dot matches the expanded dot",
                 info->name);
        check(fabsf(actual - expected) <= 1e-3f * (fabsf(expected) + 1.0f), label);
    }
}

/* --- refusals ----------------------------------------------------------- */

static void test_refusals(void) {
    printf("refusals\n");
    float out[HNX_BLOCK_SIZE];
    unsigned char block[64] = {0};

    check(hnx_type_lookup(42) == NULL, "an upstream type id is not ours");
    check(hnx_is_hnx_type(HNX_TYPE_IQ0_5) == 1, "IQ0.5 is ours");
    check(hnx_is_hnx_type(2) == 0, "Q4_0 is not");
    check(hnx_block_bytes(999) == 0, "an unknown type has no block size");
    check(hnx_dequantize_block(999, block, out) != 0, "an unknown type refuses");
    /* Zero rather than a partial write: a caller that ignores the return
     * value gets zeros, not uninitialised memory. */
    check(hnx_dequantize_rows(999, block, out, 1) == 0, "and writes nothing");
    check(hnx_dequantize_block(HNX_TYPE_IQ0_5, NULL, out) != 0, "NULL src refuses");
    check(hnx_dequantize_block(HNX_TYPE_IQ0_5, block, NULL) != 0, "NULL dst refuses");
    check(hnx_vec_dot(999, block, out, 1) == 0.0f, "an unknown type dots to zero");

    check(hnx_type_by_name("IQ0.5_XXXL") != NULL, "the hyprslug name resolves");
    check(hnx_type_by_name("IQ0.5_XXXL")->type == HNX_TYPE_IQ0_5, "to the right id");
    check(hnx_type_by_name("Q4_K_M") == NULL, "a llama.cpp name does not");
    check(hnx_type_by_name(NULL) == NULL, "NULL does not crash");
}

/* --- vectors from Python ------------------------------------------------ */

/* Record layout, little-endian throughout:
 *   int32  type id
 *   int32  block byte count
 *   bytes  the packed block
 *   float  x 256, what hypernix.quant.subbit decoded it to
 * Repeated until EOF. */
static int compare_vectors(const char *path) {
    FILE *handle = fopen(path, "rb");
    if (handle == NULL) {
        fprintf(stderr, "FAIL vectors: cannot open %s\n", path);
        return 1;
    }
    size_t records = 0;
    int32_t header[2];
    while (fread(header, sizeof(int32_t), 2, handle) == 2) {
        const int type = (int)header[0];
        const size_t bytes = (size_t)header[1];
        const hnx_type_info *info = hnx_type_lookup(type);
        if (info == NULL) {
            fprintf(stderr, "FAIL vectors: record %zu has unknown type %d\n",
                    records, type);
            fclose(handle);
            return 1;
        }
        if (bytes != info->block_bytes) {
            fprintf(stderr,
                    "FAIL vectors: %s record %zu says %zu bytes, C says %zu\n",
                    info->name, records, bytes, info->block_bytes);
            fclose(handle);
            return 1;
        }
        unsigned char packed[64];
        float expected[HNX_BLOCK_SIZE];
        if (fread(packed, 1, bytes, handle) != bytes ||
            fread(expected, sizeof(float), HNX_BLOCK_SIZE, handle) != HNX_BLOCK_SIZE) {
            fprintf(stderr, "FAIL vectors: record %zu is truncated\n", records);
            fclose(handle);
            return 1;
        }

        float actual[HNX_BLOCK_SIZE];
        if (hnx_dequantize_block(type, packed, actual) != 0) {
            fprintf(stderr, "FAIL vectors: %s record %zu did not decode\n",
                    info->name, records);
            fclose(handle);
            return 1;
        }
        for (size_t i = 0; i < HNX_BLOCK_SIZE; i++) {
            /* Exact. Both sides multiply the same FP16 scale by +/-1, so
             * there is no rounding to be tolerant of -- and a tolerance
             * here would hide precisely the off-by-one bit errors this
             * test exists to catch. */
            if (actual[i] != expected[i]) {
                fprintf(stderr,
                        "FAIL vectors: %s record %zu element %zu: "
                        "C %.9g, Python %.9g\n",
                        info->name, records, i, (double)actual[i],
                        (double)expected[i]);
                fclose(handle);
                return 1;
            }
        }
        records++;
    }
    fclose(handle);
    if (records == 0) {
        fprintf(stderr, "FAIL vectors: %s held no records\n", path);
        return 1;
    }
    printf("  ok   %zu blocks decode identically to hypernix.quant.subbit\n",
           records);
    return 0;
}

int main(int argc, char **argv) {
    printf("ggml-hnx selftest\n\n");
    test_block_sizes();
    test_fp16();
    test_sign_mapping();
    test_round_trip_and_dot();
    test_refusals();

    if (argc > 1) {
        printf("cross-check against Python\n");
        failures += compare_vectors(argv[1]);
    } else {
        printf("\n(no vector file given; run with tools/gen_vectors.py output\n"
               " to cross-check against hypernix.quant.subbit)\n");
    }

    printf("\n%s\n", failures ? "FAILED" : "all checks passed");
    return failures ? 1 : 0;
}
