#!/usr/bin/env python3
"""Decide what the Xcode project should contain, before generating it.

Run this immediately before `xcodegen generate`; CI does, and so should
anyone building by hand.

Why this exists
---------------
The app links llama.cpp when it is vendored and must build without it
when it is not — someone changing a view should not need a
twenty-minute engine compile, and CI runs the simulator tests on a
checkout that has never built it.

The first attempt at that expressed the dependency in `project.yml`
with XcodeGen's ``optional: true``, on the assumption that "optional"
meant "skip when the file is absent". It does not. ``optional`` sets
*weak linking* — a dynamic-linker property — and the framework still
has to exist at build time. So a checkout without it failed with::

    error: There is no XCFramework found at '.../ios/vendor/llama.xcframework'

...at build time, on a project that generated cleanly. A test asserting
the YAML said ``optional`` passed the whole time, which is the useful
lesson: it checked the spelling, not the behaviour.

So the decision is made here, in Python, where it can be tested: this
writes ``project.generated.yml`` next to ``project.yml`` — next to it,
so every relative path in the spec still resolves — either with the
dependency or without it, and writes the matching compilation flag.
Both derive from one filesystem check, so they cannot disagree.
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

IOS_DIR = Path(__file__).resolve().parent.parent
SPEC = IOS_DIR / "project.yml"
GENERATED = IOS_DIR / "project.generated.yml"
FRAMEWORK = IOS_DIR / "vendor" / "llama.xcframework"
XCCONFIG = IOS_DIR / "vendor" / "LocalLlama.xcconfig"

# The dependency block, injected into the HyperLink target when the
# engine is present.
#
# `embed: true`, because llama.framework is **dynamic**. This said
# `false` for a long time, on this reasoning:
#
#     Upstream's build-xcframework.sh builds with BUILD_SHARED_LIBS=OFF,
#     so this is a *static* framework: its code is linked into the app
#     binary, and embedding it would copy a static archive into the
#     bundle for nothing.
#
# The flag is real and the conclusion does not follow. Upstream passes
# BUILD_SHARED_LIBS=OFF for the *component* libraries and then combines
# them into a dynamic one — its own comment reads "Create dynamic
# libraries from static libraries", and it sets
# `install_name=@rpath/llama.framework/llama` on the result. So the app
# links against an @rpath dylib that was never copied into the bundle,
# and dyld kills it the instant it starts:
#
#     namespace: DYLD, indicator: "Library missing"
#     Library not loaded: @rpath/llama.framework/llama
#       tried: .../App.app/Frameworks/llama.framework/llama (no such file)
#
# Reading the cmake flag and stopping is what produced the wrong answer;
# the install_name is the thing that decides it.
DEPENDENCY_BLOCK = """    dependencies:
      # Written by ios/scripts/prepare_project.py because the engine is
      # vendored. Dynamic (upstream combines the static libs into one
      # dylib with install_name @rpath/llama.framework/llama), so it has
      # to be embedded or dyld cannot find it at launch.
      - framework: vendor/llama.xcframework
        embed: true
"""

MARKER = "# @prepare_project: dependencies"

ENTITLEMENTS = IOS_DIR / "HyperLink" / "HyperLink.entitlements"
ENTITLEMENTS_MARKER = "# @prepare_project: entitlements"

# Injected only when the build says it has Apple's CarPlay grant.
#
# `com.apple.developer.carplay-communication` is a *restricted*
# entitlement: it must be present in the provisioning profile, and Apple
# grants it per app on request. An app signed with an entitlement its
# profile does not carry is not an app with one feature missing -- it is
# killed at launch by amfid, EXC_CRASH (SIGKILL) with termination reason
# CODESIGNING, before any of its own code runs.
#
# The project believed the opposite. The entitlements file said a build
# without the grant "will compile, install, and show nothing in a car -
# with no error anywhere", and on the strength of that the setting was
# unconditional.
#
# Gating it is still right, but it fixed nothing that was observed. It
# was added while chasing a crash-on-launch, on the theory that this
# entitlement caused it; that theory is disproven. An unsigned archive
# carries no entitlements file, and the shipped IPA is unsigned, so this
# never reached a phone. It matters only for a build that is signed
# without the grant.
ENTITLEMENTS_BLOCK = """        CODE_SIGN_ENTITLEMENTS: HyperLink/HyperLink.entitlements
"""

ON = """// Generated by ios/scripts/prepare_project.py — the engine is vendored.
HNX_LOCAL_LLAMA = HNX_LOCAL_LLAMA
"""

OFF = """// Generated by ios/scripts/prepare_project.py — no engine vendored.
//
// LlamaRunner.swift compiles out and LocalInference falls back to
// EchoRunner, which tells the user this build has no local engine.
// Build one with ios/scripts/build_llama_xcframework.sh.
HNX_LOCAL_LLAMA =
"""


def engine_present(framework: Path = FRAMEWORK) -> bool:
    """Is there actually a usable xcframework there?

    A directory alone is not enough: an interrupted copy leaves one
    behind with nothing in it, and xcodebuild's complaint about that is
    considerably less clear than this one. Info.plist is what makes an
    xcframework an xcframework.
    """
    return (framework / "Info.plist").is_file()


def render(spec_text: str, *, with_engine: bool, with_carplay: bool = False) -> str:
    """The generated spec, from the committed one."""
    for marker in (MARKER, ENTITLEMENTS_MARKER):
        if marker not in spec_text:
            raise SystemExit(
                f"::error::{SPEC.name} has no '{marker}' line. "
                f"prepare_project.py substitutes there and cannot find it."
            )
    block = DEPENDENCY_BLOCK if with_engine else ""
    header = (
        "# GENERATED — do not edit. Written by ios/scripts/prepare_project.py\n"
        "# from project.yml. Edit that file instead.\n"
        f"# Engine vendored: {with_engine}\n"
        f"# CarPlay entitlement: {with_carplay}\n\n"
    )
    # The *whole line*, indentation included. Replacing only the marker
    # text leaves its four spaces behind, and those merge with the next
    # line: `    settings:` became `        settings:` and the spec
    # stopped parsing. Indentation is load-bearing in YAML, so a
    # substring replace inside an indented block is the wrong tool.
    body = re.sub(rf"^[ \t]*{re.escape(MARKER)}[ \t]*\n", block, spec_text, flags=re.M)
    if body == spec_text:
        raise SystemExit(f"::error::could not substitute the '{MARKER}' line")
    entitlements = ENTITLEMENTS_BLOCK if with_carplay else ""
    after = re.sub(
        rf"^[ \t]*{re.escape(ENTITLEMENTS_MARKER)}[ \t]*\n",
        entitlements, body, flags=re.M,
    )
    if after == body:
        raise SystemExit(
            f"::error::could not substitute the '{ENTITLEMENTS_MARKER}' line"
        )
    return header + after


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="report what would be written, change nothing",
    )
    parser.add_argument(
        "--carplay", action="store_true",
        help=(
            "include the CarPlay entitlement. Only pass this when the "
            "build is signed with a provisioning profile that carries "
            "com.apple.developer.carplay-communication -- Apple grants "
            "it per app on request. Without that profile the signed app "
            "is killed at launch, so this is off by default."
        ),
    )
    parser.add_argument(
        "--require-engine", action="store_true",
        help=(
            "fail if llama.cpp is not vendored. For a build that asked "
            "for the engine: falling back to EchoRunner is right for a PR "
            "and is a silently inert release."
        ),
    )
    args = parser.parse_args(argv)

    # FRAMEWORK read here rather than taken from engine_present's default
    # argument: a default binds at definition time, so the two disagree
    # the moment anything points the module at a different path.
    present = engine_present(FRAMEWORK)
    if args.require_engine and not present:
        # The failure this exists for: a release asked for the engine,
        # the engine build failed or was skipped, and the IPA shipped
        # with every on-device feature quietly doing nothing. Nothing
        # said so, because the fallback is the *correct* behaviour for a
        # build that did not ask.
        raise SystemExit(
            "::error::--require-engine was passed and there is no "
            f"llama.xcframework at {FRAMEWORK}. This build would ship "
            "EchoRunner, so on-device inference would be inert. Run "
            "ios/scripts/build_llama_xcframework.sh first, or drop "
            "--require-engine for a build that genuinely does not need it."
        )
    # The environment variable is for the workflow, which decides this
    # from whether signing secrets exist and cannot easily add a flag to
    # a shared step; the flag is for a person at a terminal. Either is
    # an explicit "yes", which is the point -- nothing infers the grant.
    carplay = args.carplay or os.environ.get("HNX_CARPLAY_ENTITLEMENT") == "1"
    spec = render(
        SPEC.read_text(encoding="utf-8"),
        with_engine=present,
        with_carplay=carplay,
    )

    state = "ON — llama.cpp linked" if present else "OFF — EchoRunner only"
    carplay_state = (
        "ON — this build claims Apple's grant"
        if carplay else
        "OFF — no entitlement, so the app launches"
    )
    if args.check:
        print(f"on-device inference: {state}")
        print(f"CarPlay entitlement: {carplay_state}")
        return 0

    GENERATED.write_text(spec, encoding="utf-8")
    XCCONFIG.parent.mkdir(parents=True, exist_ok=True)
    XCCONFIG.write_text(ON if present else OFF, encoding="utf-8")

    print(f"::notice::on-device inference is {state}")
    print(f"::notice::CarPlay entitlement is {carplay_state}")
    print(f"wrote {GENERATED.relative_to(IOS_DIR)} and "
          f"{XCCONFIG.relative_to(IOS_DIR)}")
    if not present:
        print("      build the engine with scripts/build_llama_xcframework.sh")
    return 0


if __name__ == "__main__":
    sys.exit(main())
