#!/usr/bin/env python3
"""Decide what the Xcode project should contain, before generating it.

Run this immediately before `xcodegen generate`; CI does, and so should
anyone building by hand.

Why this exists
---------------
The app links llama.cpp when it is vendored and must build without it
when it is not — someone changing a view should not need a
twenty-minute engine compile, and CI runs the simulator tests on a
checkout that has never built it.

The first attempt at that expressed the dependency in `project.yml`
with XcodeGen's ``optional: true``, on the assumption that "optional"
meant "skip when the file is absent". It does not. ``optional`` sets
*weak linking* — a dynamic-linker property — and the framework still
has to exist at build time. So a checkout without it failed with::

    error: There is no XCFramework found at '.../ios/vendor/llama.xcframework'

...at build time, on a project that generated cleanly. A test asserting
the YAML said ``optional`` passed the whole time, which is the useful
lesson: it checked the spelling, not the behaviour.

So the decision is made here, in Python, where it can be tested: this
writes ``project.generated.yml`` next to ``project.yml`` — next to it,
so every relative path in the spec still resolves — either with the
dependency or without it, and writes the matching compilation flag.
Both derive from one filesystem check, so they cannot disagree.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

IOS_DIR = Path(__file__).resolve().parent.parent
SPEC = IOS_DIR / "project.yml"
GENERATED = IOS_DIR / "project.generated.yml"
FRAMEWORK = IOS_DIR / "vendor" / "llama.xcframework"
XCCONFIG = IOS_DIR / "vendor" / "LocalLlama.xcconfig"

# The dependency block, injected into the HyperLink target when the
# engine is present.
#
# `embed: false` is not an oversight. Upstream's build-xcframework.sh
# builds with BUILD_SHARED_LIBS=OFF, so this is a *static* framework:
# its code is linked into the app binary, and embedding it would copy a
# static archive into the bundle for nothing — App Store validation
# rejects that, and it is pure size in the meantime. Embedding is for
# dynamic frameworks.
DEPENDENCY_BLOCK = """    dependencies:
      # Written by ios/scripts/prepare_project.py because the engine is
      # vendored. Static (BUILD_SHARED_LIBS=OFF upstream), so linked and
      # not embedded.
      - framework: vendor/llama.xcframework
        embed: false
"""

MARKER = "# @prepare_project: dependencies"

ON = """// Generated by ios/scripts/prepare_project.py — the engine is vendored.
HNX_LOCAL_LLAMA = HNX_LOCAL_LLAMA
"""

OFF = """// Generated by ios/scripts/prepare_project.py — no engine vendored.
//
// LlamaRunner.swift compiles out and LocalInference falls back to
// EchoRunner, which tells the user this build has no local engine.
// Build one with ios/scripts/build_llama_xcframework.sh.
HNX_LOCAL_LLAMA =
"""


def engine_present(framework: Path = FRAMEWORK) -> bool:
    """Is there actually a usable xcframework there?

    A directory alone is not enough: an interrupted copy leaves one
    behind with nothing in it, and xcodebuild's complaint about that is
    considerably less clear than this one. Info.plist is what makes an
    xcframework an xcframework.
    """
    return (framework / "Info.plist").is_file()


def render(spec_text: str, *, with_engine: bool) -> str:
    """The generated spec, from the committed one."""
    if MARKER not in spec_text:
        raise SystemExit(
            f"::error::{SPEC.name} has no '{MARKER}' line. prepare_project.py "
            f"injects the framework dependency there and cannot find it."
        )
    block = DEPENDENCY_BLOCK if with_engine else ""
    header = (
        "# GENERATED — do not edit. Written by ios/scripts/prepare_project.py\n"
        "# from project.yml. Edit that file instead.\n"
        f"# Engine vendored: {with_engine}\n\n"
    )
    # The *whole line*, indentation included. Replacing only the marker
    # text leaves its four spaces behind, and those merge with the next
    # line: `    settings:` became `        settings:` and the spec
    # stopped parsing. Indentation is load-bearing in YAML, so a
    # substring replace inside an indented block is the wrong tool.
    body = re.sub(rf"^[ \t]*{re.escape(MARKER)}[ \t]*\n", block, spec_text, flags=re.M)
    if body == spec_text:
        raise SystemExit(f"::error::could not substitute the '{MARKER}' line")
    return header + body


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="report what would be written, change nothing",
    )
    args = parser.parse_args(argv)

    present = engine_present()
    spec = render(SPEC.read_text(encoding="utf-8"), with_engine=present)

    state = "ON — llama.cpp linked" if present else "OFF — EchoRunner only"
    if args.check:
        print(f"on-device inference: {state}")
        return 0

    GENERATED.write_text(spec, encoding="utf-8")
    XCCONFIG.parent.mkdir(parents=True, exist_ok=True)
    XCCONFIG.write_text(ON if present else OFF, encoding="utf-8")

    print(f"::notice::on-device inference is {state}")
    print(f"wrote {GENERATED.relative_to(IOS_DIR)} and "
          f"{XCCONFIG.relative_to(IOS_DIR)}")
    if not present:
        print("      build the engine with scripts/build_llama_xcframework.sh")
    return 0


if __name__ == "__main__":
    sys.exit(main())
