#!/usr/bin/env python3
"""Generate examples/t1api/API-EXAMPLES.md and the OpenAPI schema.

Spec deliverables #6 (OpenAPI schema) and #9 (example requests and
responses for every endpoint).

Both are *generated by driving a real server*, not written by hand. A
hand-written example is a claim about the API; a generated one is a
recording of it. When a response shape changes, this regenerates and the
diff shows up in review — which is the only way an example file stays
true a year later.

    python scripts/t1api_examples.py

Writes:
    examples/t1api/API-EXAMPLES.md
    examples/t1api/openapi.json
"""
from __future__ import annotations

import json
import secrets
import shutil
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

OUT_DIR = REPO_ROOT / "examples" / "t1api"

# Values that change every run. Pinned in the output so regenerating
# produces a reviewable diff of *behaviour* rather than a wall of new
# uuids and timestamps.
_VOLATILE_KEYS = {
    # Credential-shaped fields first. These are ephemeral values from a
    # throwaway keystore that this script deletes on exit, so none of them
    # is live — but a generated document that prints something key-shaped
    # teaches the wrong habit to whoever reads it next, and the shape is
    # what the example is for. The value never survives to the page.
    "key", "token", "signature",
    "request_id", "ts", "created_at", "updated_at", "assigned_at", "expires_at",
    "started_at", "finished_at", "audit_id", "event_id", "job_id", "module_id",
    "server_id", "entry_id", "transaction_id", "payment_token_id", "last_refresh",
    "checksum", "observed_seconds", "duration_ms", "since", "until", "basis",
    "first_ts", "key_id", "actor_key_id", "resource_id", "rotated_from",
    "hypernix_version", "t1_api_version",
}


def _stabilize(value):
    """Replace volatile values with a placeholder, recursively."""
    if isinstance(value, dict):
        return {
            k: (f"<{k}>" if k in _VOLATILE_KEYS and value[k] not in (None, "", [], {})
                else _stabilize(v))
            for k, v in value.items()
        }
    if isinstance(value, list):
        return [_stabilize(v) for v in value]
    return value


class Recorder:
    def __init__(self, client) -> None:
        self.client = client
        self.sections: list[tuple[str, list[dict]]] = []
        self._current: list[dict] = []

    def section(self, title: str) -> None:
        self._current = []
        self.sections.append((title, self._current))

    def call(self, method: str, path: str, *, note: str = "", **kwargs) -> dict:
        headers = kwargs.pop("headers", None)
        response = self.client.request(method, path, headers=headers, **kwargs)
        try:
            body = response.json()
        except ValueError:
            body = {"<non-json body>": response.text[:200]}
        self._current.append(
            {
                "method": method.upper(),
                "path": path,
                "note": note,
                "request": _stabilize(kwargs.get("json")),
                "params": _stabilize(kwargs.get("params")),
                "status": response.status_code,
                "response": _stabilize(body),
                "authenticated": bool(headers and "Authorization" in headers),
            }
        )
        return body


def build() -> None:
    try:
        from fastapi.testclient import TestClient
    except ImportError:
        raise SystemExit(
            "This script drives a real server, so it needs the test extra:\n"
            "    pip install 'hypernix[t1api-test]'"
        ) from None

    from hypernix.security.gatekeeper import Gatekeeper
    from hypernix.security.keymaster import Keymaster, KeyScope, KeyType
    from hypernix.t1api.app import create_app
    from hypernix.t1api.config import T1APIConfig
    from hypernix.t1api.registry import ModelRegistry, ModelStatus
    from hypernix.t1api.routing import RoutingTable

    workdir = Path(tempfile.mkdtemp(prefix="t1api-examples-"))
    try:
        km = Keymaster(store_dir=workdir / "km", auto_rotate=False)
        gk = Gatekeeper(keymaster=km, data_dir=workdir / "gk", log_to_file=False)

        # The shipped example registry, promoted to routable so the
        # examples show real responses rather than empty lists. The
        # entries are still the spec's placeholders — see the note the
        # generated document carries.
        registry = ModelRegistry.load(include_examples=True)
        for entry in registry.list():
            entry.status = ModelStatus.AVAILABLE
            entry.is_example_entry = False
            registry.register(entry)

        config = T1APIConfig(
            # Made fresh each run: a secret written into the repo is a
            # secret somebody copies into a real .env.
            token_secret=secrets.token_hex(32),
            db_path=str(workdir / "t1.sqlite3"),
            module_storage_dir=str(workdir / "modules"),
            deploy_secret=secrets.token_hex(32),
        )
        app = create_app(
            config=config, keymaster=km, gatekeeper=gk, registry=registry,
            routing_table=RoutingTable.load(),
        )
        client = TestClient(app, client=("127.0.0.1", 5000))

        admin_meta = km.create(
            key_type=KeyType.ADMIN, scopes={KeyScope.ADMIN, KeyScope.READ, KeyScope.WRITE}
        )
        user_meta = km.create(key_type=KeyType.USER, scopes={KeyScope.READ, KeyScope.WRITE})
        real_admin = {"Authorization": f"Bearer {admin_meta.key}"}
        real_user = {"Authorization": f"Bearer {user_meta.key}"}

        rec = Recorder(client)

        # --- health / status -------------------------------------------
        rec.section("Health and status")
        rec.call("GET", "/health", note="No auth. Touches no database — safe for a load balancer.")
        rec.call("GET", "/status", note="Which protections are on, and which secrets are set (never their values).")
        rec.call("GET", "/config", note="An explicit allowlist of settings. A secret cannot leak here by being forgotten.")

        # --- auth ------------------------------------------------------
        rec.section("Authentication")
        rec.call("POST", "/auth/t1/validate", json={"key": "<T1_KEY>"},
                 note="Validate a raw key. The response never echoes the key back.")
        rec.call("POST", "/auth/token", json={"key": "<T1_KEY>", "scopes": ["read"], "ttl_seconds": 3600},
                 note="Exchange a key for a short-lived scoped token. A token can only narrow the key's scopes, never widen them.")
        # Rotation invalidates the key it was called with, so this uses a
        # throwaway rather than the user key the rest of the document
        # depends on — which is itself the behaviour being demonstrated.
        throwaway = km.create(key_type=KeyType.USER, scopes={KeyScope.READ})
        rec.call("POST", "/auth/t1/rotate",
                 headers={"Authorization": f"Bearer {throwaway.key}"},
                 note="Rotate your own credential. The only endpoint that returns a raw key, because it mints a new one — the old key stops working immediately.")
        rec.call("POST", "/auth/t1/admin/rotate",
                 json={"target_key_id": "<TARGET_KEY_ID>", "promote_to_admin": True},
                 headers=real_user,
                 note="Admin-only. Shown here refused, because promoting a key is exactly the operation a non-admin must not reach.")

        # --- models ----------------------------------------------------
        rec.section("Models")
        rec.call("GET", "/models", note="The registry is the only source of models. Nothing else can name one.")
        rec.call("GET", "/models/nanonix-nano")
        rec.call("GET", "/models/does-not-exist",
                 note="Unregistered ids always return MODEL_NOT_SUPPORTED — never a fall-through to a client-supplied path.")
        rec.call("GET", "/models/nanonix-nano/availability")
        rec.call("GET", "/models/nanonix-nano/usage", headers=real_user)
        rec.call("POST", "/models/route", json={"input_tokens": 1200}, headers=real_user,
                 note="Automatic routing. The plan comes from the key's assignment, not the request.")
        rec.call("POST", "/models/route", json={"plan": "enterprise", "input_tokens": 10}, headers=real_user,
                 note="Claiming a plan you do not hold is refused rather than honoured.")

        # --- usage / cost ----------------------------------------------
        app.state.t1_usage_store.record(
            key_id=user_meta.key_id, model_id="nanonix-nano",
            input_tokens=12_000, output_tokens=3_400, server_id="srv-01",
        )
        rec.section("Usage and cost")
        rec.call("GET", "/usage/current", headers=real_user)
        rec.call("GET", "/usage/remaining", params={"model_id": "nanonix-nano"}, headers=real_user)
        rec.call("GET", "/usage/history", params={"range": "24h", "limit": 5}, headers=real_user)
        rec.call("GET", "/usage/by", params={"group_by": "model_id", "range": "24h"}, headers=real_user,
                 note="One endpoint for usage by model / key / server / module / user / account.")
        rec.call("GET", "/usage/cost", params={"range": "30d", "forecast": "true"}, headers=real_user,
                 note="A forecast states the window it extrapolated from and how much to trust it.")
        rec.call("POST", "/usage/estimate",
                 json={"model_id": "nanonix-nano", "input_tokens": 5000}, headers=real_user,
                 note="Records nothing and reserves nothing. Omitting output_tokens gives an upper bound.")

        # --- keys ------------------------------------------------------
        rec.section("Keys")
        rec.call("GET", "/keys", headers=real_user, note="A non-admin sees exactly one key: their own.")
        rec.call("POST", "/keys/assign",
                 json={"key_id": user_meta.key_id, "plan": "free", "account_id": "acct-demo",
                       "allowed_models": ["nanonix-nano"]},
                 headers=real_admin,
                 note="Where a key's plan — and therefore its quota and fallback chain — comes from. Admin-only.")
        rec.call("POST", "/keys/import", json={"payload": {"keys": []}}, headers=real_admin,
                 note="Imports a Keymaster export. The response carries counts and masked ids, never key material.")

        # --- servers ---------------------------------------------------
        rec.section("Servers")
        server = rec.call("POST", "/servers/register",
                          json={"name": "deploy-01", "address": "https://deploy-01.example.com"},
                          headers=real_admin,
                          note="Servers register UNTRUSTED. Only an admin can promote one, and only a trusted server can receive a module.")
        server_id = server["server"]["server_id"]
        rec.call("GET", "/servers", headers=real_admin)
        rec.call("PATCH", f"/servers/{server_id}", json={"trust_level": "trusted"}, headers=real_admin,
                 note="Promotion is audited — it is the gate every module push checks.")
        rec.call("POST", "/servers/register",
                 json={"name": "metadata", "address": "http://169.254.169.254/latest/meta-data"},
                 headers=real_admin,
                 note="The SSRF guard rejects the cloud-metadata endpoint unconditionally.")
        rec.call("DELETE", f"/servers/{server_id}", headers=real_admin,
                 note="Destructive operations need ?confirm=true.")

        # --- modules ---------------------------------------------------
        rec.section("Modules")
        module = rec.call("POST", "/modules/create",
                          json={"name": "demo-module", "version": "1.0.0"}, headers=real_user)
        module_id = module["module"]["module_id"]
        rec.call("GET", "/modules", headers=real_user)
        rec.call("POST", "/modules/upload/remote", params={"module_id": module_id},
                 json={"source_url": "https://cdn.example.com/demo-module-1.0.0.bin"},
                 headers=real_user,
                 note="Registers and validates a source URL. It is NOT fetched here — POST /modules/{id}/fetch does that as a job.")
        rec.call("POST", f"/modules/{module_id}/deploy", json={"server_ids": ["<SERVER_ID>"]},
                 headers=real_user,
                 note="Multi-server deployment. Every target is trust-checked before the job is queued.")

        # --- jobs / events ---------------------------------------------
        rec.section("Jobs and events")
        rec.call("POST", "/jobs", json={"kind": "not-a-registered-kind", "payload": {}},
                 headers=real_user,
                 note="An unregistered job kind is NOT_SUPPORTED — a stable answer, not a 500.")
        rec.call("GET", "/events", params={"limit": 5},
                 note="Polling form. GET /events/stream is the SSE live tail.")

        # --- billing ---------------------------------------------------
        rec.section("Billing")
        rec.call("GET", "/billing/balance", headers=real_user)
        minted = rec.call("POST", "/billing/payment-token", json={"amount": 25.0, "currency": "USD"},
                          headers=real_admin,
                          note="Admin-only. The raw token is returned exactly once and stored only as a hash — capture it here or it is gone.")
        token = minted.get("token")
        if token:
            rec.call("POST", "/billing/redeem", json={"token": "<PAYMENT_TOKEN>"}, headers=real_user,
                     note="Redemption is single-use; a second attempt returns PAYMENT_TOKEN_ALREADY_REDEEMED.")
            client.post("/billing/redeem", json={"token": token}, headers=real_user)
            rec.call("POST", "/billing/redeem", json={"token": "<THE SAME PAYMENT_TOKEN>"},
                     headers=real_user, note="The second attempt.")
        rec.call("GET", "/billing/transactions", headers=real_user,
                 note="Transaction and payment-token ids are masked in every response.")

        # --- security / audit ------------------------------------------
        rec.section("Security and audit")
        rec.call("GET", "/security/network", headers=real_admin)
        rec.call("POST", "/security/network/blacklist",
                 json={"cidr": "203.0.113.0/24", "reason": "abuse"}, headers=real_admin)
        rec.call("POST", "/security/network/whitelist",
                 json={"cidr": "100.64.0.0/10", "reason": "tailnet"}, headers=real_admin)
        rec.call("POST", "/security/limits",
                 json={"subject_type": "key", "subject_id": "<KEY_ID>", "requests_per_window": 60,
                       "window_seconds": 60, "reason": "noisy client"},
                 headers=real_admin,
                 note="waiter -r. A forced limit only ever tightens — it applies in addition to the configured rules.")
        rec.call("GET", "/security/rate-limits", headers=real_user,
                 note="Your own remaining budget, so you can back off before a 429 rather than after one.")
        rec.call("GET", "/audit", params={"limit": 3}, headers=real_admin,
                 note="Admin-only, and reading it is itself audited.")
        rec.call("GET", "/audit", headers=real_user,
                 note="A non-admin is refused — the audit log is a map of who administers this deployment.")

        _write_markdown(rec)
        _write_openapi(client)
    finally:
        shutil.rmtree(workdir, ignore_errors=True)


def _write_markdown(rec: Recorder) -> None:
    lines = [
        "# HyperNix T1 API — example requests and responses",
        "",
        "**Generated by `scripts/t1api_examples.py`. Do not edit by hand.**",
        "",
        "Every exchange below was recorded from a real server rather than",
        "written out, so these are a recording of the API's behaviour and not",
        "a claim about it. Re-run the script after changing a response shape",
        "and the diff shows exactly what a client would see differently.",
        "",
        "Volatile values (ids, timestamps, request ids) are replaced with",
        "`<placeholder>` so regenerating produces a reviewable diff instead of",
        "a wall of new uuids. Keys and tokens are placeholders throughout —",
        "no real credential is ever recorded here.",
        "",
        "The models shown are the shipped **example registry** entries, which",
        "the spec describes as placeholders that are not real models. A live",
        "deployment points `T1_MODEL_REGISTRY_PATH` at its own data.",
        "",
        "## Contents",
        "",
    ]
    for title, _ in rec.sections:
        anchor = title.lower().replace(" ", "-")
        lines.append(f"- [{title}](#{anchor})")
    lines.append("")

    for title, calls in rec.sections:
        lines.extend([f"## {title}", ""])
        for call in calls:
            auth = " *(authenticated)*" if call["authenticated"] else ""
            lines.append(f"### `{call['method']} {call['path']}`{auth}")
            lines.append("")
            if call["note"]:
                lines.extend([call["note"], ""])
            if call["params"]:
                lines.extend(["Query:", "", "```", json.dumps(call["params"], indent=2), "```", ""])
            if call["request"] is not None:
                lines.extend(
                    ["Request:", "", "```json", json.dumps(call["request"], indent=2), "```", ""]
                )
            lines.extend(
                [
                    f"Response `{call['status']}`:",
                    "",
                    "```json",
                    json.dumps(call["response"], indent=2),
                    "```",
                    "",
                ]
            )

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    target = OUT_DIR / "API-EXAMPLES.md"
    target.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {target.relative_to(REPO_ROOT)} ({len(lines)} lines)")


def _write_openapi(client) -> None:
    schema = client.get("/openapi.json").json()
    target = OUT_DIR / "openapi.json"
    target.write_text(json.dumps(schema, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"wrote {target.relative_to(REPO_ROOT)} ({len(schema['paths'])} paths)")


if __name__ == "__main__":
    build()
